### ISSUE TITLE
[LC0012] Too strict when used in combination with vars / fields

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#154] opened 2022-02-24 09:52 UTC
LC0012 was originally intented to avoid Page.Run(**18**), Codeunit.Run(**80**), ... So to avoid hardcoded integer instead of Page::, Database::, ...

We do have lots of generic modules that can be configured by the user, where the RecRef.Open, Page.RunModal, ... is not using a hardcoded id, but a value originating from another variable, from a setup page / field value.

`RecRef.Open("Source Table");`

To me it seems the above does not need a pragma, since there's no hardcoded values used.

It is an option to loosen the LC0012 rule?

**Comment by StefanMaron** [comment] 2022-02-24 10:11
Well that should not be warned. But I can not reproduce that:  
![image](https://user-images.githubusercontent.com/24838311/155504089-ec64c27b-de99-448b-9008-87fa03e0957b.png)

**Comment by fvet** [comment] 2022-02-24 11:12
Could it be because of the ArgumentOutofRangeExceptions (for LC0003 / LC0017) when loading my workspace?

![image](https://user-images.githubusercontent.com/25268332/155513539-417814d9-2696-48cd-a0ac-c2152c9e0487.png)

Not sure how I can debug / find the conflicting source code...

**Comment by StefanMaron** [comment] 2022-02-24 12:31
I dont think that this correlates.

LC0003: I took a look at the code of that rule and I dont think I can give any usefull hints to find the code leading to this error. If I will find the time I will need to rework the logic of that rule. Since I am now able to debug, I have deeper insights in the structures of the analyzer objects enabling me to write better code.

LC0017: is this the same as #149? Can you check If you have the latest version?

**Comment by StefanMaron** [comment] 2022-02-25 17:22
I added Rule0000. I call this in the catch block. Its of type info, its just meant to help us find those lines of code with make the linter crash

**Comment by fvet** [comment] 2022-02-27 17:58
Currently running on **v0.1.2.**
No LC0000 warnings.

![image](https://user-images.githubusercontent.com/25268332/155893911-9d409269-18ac-4f50-b9bb-fd90fe596626.png)

**Comment by StefanMaron** [comment] 2022-03-22 09:26
is this also related to AL Runtime version 9 ?

**Comment by fvet** [comment] 2022-03-22 22:40
This issue was logged while running on AL runtime v9.
On v8.4.x it does not occur.

**Comment by StefanMaron** [comment] 2022-04-01 07:50
This should be fixed now with version [v0.25.1](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.25.1)

**Closed** 2022-04-22 10:42 UTC
Labels: bug, nextmajor
