### ISSUE TITLE
LC0052 interfaces

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#561] opened 2024-03-12 12:07 UTC
When I declare an internal interface with methods. (Interface is set to internal, allowing use to add methods without breaking things)
And implement the interface by adding the methods in a public codeunit, LC0052 pops up. (Codeunit was public due to legacy, so we ended up adding the interface related functions as internal in the codeunit)

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/25268332/357839b4-f22e-4202-8dfb-e0002ad18a47)

In my opinion, the LC0052 should not raise a warning here? Functions are not explicitly referenced, but referenced via the interface instead.

**Comment by fvet** [comment] 2024-03-12 12:08
`The internal method PreProcessIncomingMessage in Codeunit ESCN IC Message Order (Access = Public) is declared but never used.`

**Comment by Arthurvdv** [comment] 2024-03-14 11:47
This should now be resolved in the (pre)release version of [v0.30.15](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.15) of the LinterCop.

**Comment by rvanbekkum** [comment] 2024-03-17 09:38
The changes that were made are now leading to false negatives. It should not completely skip procedures in codeunits that implement an interface, because if you do that it skips procedures that are not part of the interface.
I think instead the method that checks if a procedure implements an interface procedure coild/should be adjusted slightly. 😉

**Comment by Arthurvdv** [comment] 2024-03-18 15:56
@rvanbekkum , you're right, thank you for bringing this to our attention.

I need to verify if the procure is declared in the interface and then skip these.

**Comment by rvanbekkum** [comment] 2024-03-18 16:36
That's already been accounted for in the current implementation, but maybe there's an issue with the scenario in which the access modifiers of the procedures are not matching? Would need to be checked though, that's just a guess.

**Comment by Arthurvdv** [comment] 2024-03-30 11:01
@rvanbekkum, Thanks! That validation was are hiding in plain sight somehow 😅

I've moved this validation a bit up in the chain to early exclude procedures that are part of the interface.

**Comment by Arthurvdv** [comment] 2024-04-22 07:17
Version [v0.30.16](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.16) of the LinterCop is now released. Is it possible to verify of the issue is now resolved?

**Closed** 2024-05-19 08:05 UTC
Labels: bug, Resolved
