### ISSUE TITLE
LC0005 ControlAddIn

### ISSUE THREAD

**Issue by FlorianSchlangen** [StefanMaron/BusinessCentral.LinterCop#564] opened 2024-03-15 15:26 UTC
When using the ControlAddIn data type as a parameter, I receive the message "Wrong casing detected". No matter which notation is used.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/124282876/b354ad9c-7512-4179-bb54-e0d444c0935f)

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/124282876/752ca5ea-5dfb-4b6d-b24d-b2c16ccb731c)

**Comment by Arthurvdv** [comment] 2024-03-30 13:45
Thank you for reporting this!

This should now be resolved in the (pre)release version of [v0.30.16](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.16) of the LinterCop.

**Comment by FlorianSchlangen** [comment] 2024-04-02 14:40
Looks good! Thanks for the quick implementation.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/124282876/353023af-e52f-45eb-87fc-c09f68ab1a55)

**Comment by Arthurvdv** [comment] 2024-04-22 07:16
Version [v0.30.16](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.16) of the LinterCop is now released. Is it possible to verify of the issue is now resolved?

**Closed** 2024-05-16 15:22 UTC
Labels: bug, Resolved
