### ISSUE TITLE
LC0051 - Gives Possible Overflow but it shouldn't

### ISSUE THREAD

**Issue by guidorobben** [StefanMaron/BusinessCentral.LinterCop#549] opened 2024-02-26 10:09 UTC
In certain cases, warning LC0051 is show when there is now problem. When setting the filter on text fields that are bigger then the field itself should not give a problem. I tested this by setting the filter with a value bigger then 100 on the field and it didn't result in an error.

ImportLine."Contact Name" is Text[100];

```
local procedure FindExistingContacts()
var
    Contact: Record Contact;
begin
    Contact.SetFilter(Name, '%1', '@' + ImportLine."Contact Name"); //This gives warning because this would result in length 101.
    Contact.findfirst();
end;
```

**Comment by Arthurvdv** [comment] 2024-02-26 13:04
Duplicate of https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/544

**Closed by Arthurvdv** 2024-02-26 13:04 UTC
Labels: duplicate

**Comment by guidorobben** [comment] 2024-02-26 14:09
You are right. I did look for a open issue but the #544 started with LC0050. My bad.
