### ISSUE TITLE
Wrong Warnings when there are no symbols

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#581] opened 2024-04-04 07:13 UTC
Currenlty the LinterCop reports wrong/strange warning when I open a Workspace where I haven't downloaded any symbols yet.

e.g. LC0003 is reported wrong in this context.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/56249171/df2f4882-3e8d-4f72-afc6-13927efe93d4)

Is it possible to stop the Code Analysis when there are no symbols

**Comment by Arthurvdv** [comment] 2024-04-06 07:35
The LC0003/LC0005 rules indeed create a (possible) false positive when there where now symbols downloaded yet.

This should now be resolved in the (pre)release version of [v0.30.16](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.16) of the LinterCop.

**Comment by Arthurvdv** [comment] 2024-04-22 07:15
Version [v0.30.16](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.16) of the LinterCop is now released. Is it possible to verify of the issue is now resolved?

**Closed** 2024-05-13 11:41 UTC
Labels: bug, Resolved
