### ISSUE TITLE
Invalid Cast Exception related to Rule LC0043

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#417] opened 2023-12-08 12:43 UTC
Getting this message about LC0043, I don't have any SecretText references in my code but there are a few places where I could use it but have not yet updated my code.

[{
	"resource": "/c:/Repos/Jendev/JI-InternalSystem-NEW/Legacy/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'BusinessCentral.LinterCop.Design.Rule0043SecretText' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundApplicationObjectAccess' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IFieldAccess'.\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationExtensions.GetSymbol(IOperation operation) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\Compilation\\OperationExtensions.cs:line 41\r\n   at BusinessCentral.LinterCop.Design.Rule0043SecretText.<>c.<AnalyzeHttpObjects>b__6_0(IOperation x)\r\n   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)\r\n   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at BusinessCentral.LinterCop.Design.Rule0043SecretText.AnalyzeHttpObjects(OperationAnalysisContext ctx)\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 766\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by pri-kise** [comment] 2023-12-08 12:52
Is this a duplicate of https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/409 ?

**Comment by tscottjendev** [comment] 2023-12-08 12:58
Yes, sorry, I did a search and did not find this.

FYI, as noted in #409, I am still getting the error with version 0.30.9.

**Comment by Arthurvdv** [comment] 2023-12-08 13:06
I've changed the logic in this rule on that part in the updated (pre)release version [v0.30.9](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.9).

Does this resolve the error?

**Comment by tscottjendev** [comment] 2023-12-08 13:36
It would appear to have resolved the problem.

**Closed** 2023-12-08 15:05 UTC
Labels: bug
