### ISSUE TITLE
LC0052 Error Message

### ISSUE THREAD

**Issue by MutluhanGulenc** [StefanMaron/BusinessCentral.LinterCop#520] opened 2024-01-25 12:46 UTC
When an internal procedure called on report extension it gives below error message:

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer.MethodSymbolAnalyzer.<>c__DisplayClass7_0.<AnalyzeObjectSyntax>b__0(SyntaxNode syntaxNode)
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.WalkDescendantsAndPerformAction(Action`1 action, Func`2 descendIntoChildren) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1482
   at BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer.MethodSymbolAnalyzer.AnalyzeObjectSyntax(CompilationAnalysisContext compilationAnalysisContext)
   at BusinessCentral.LinterCop.Design.Rule0052InternalProceduresNotReferencedAnalyzer.CheckApplicationObjects(CompilationAnalysisContext compilationAnalysisContext)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass48_1.<ExecuteCompilationActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 618
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1079'
```
**sample:**
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/24626753/b1b23b9c-d7db-4f9f-9cf0-cdaf6655983d)

**Comment by rvanbekkum** [comment] 2024-01-26 07:59
Can reproduce with this example. Thanks! We'll look into it!

**Comment by Arthurvdv** [comment] 2024-01-28 13:27
Duplicate of https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/517

**Closed by Arthurvdv** 2024-01-28 13:27 UTC
